version: '3'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/app/frontend/
    tmpfs:
      - /tmp
    ports:
      - 3000:3000
    depends_on:
      - backend
      - mysql

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    ports:
      - 9000:9000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 8080:8080
  
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./backend:/var/www
    depends_on:
      - frontend
      - backend

volumes:
  mysql-data: