version: '3'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/app/frontend/
    tmpfs:
      - /tmp
    ports:
      - 3000:3000
    depends_on:
      - backend
      - mysql_db

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend/
    ports:
      - 9000:9000
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql_db
    ports:
      - 8080:8080
  
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/app/backend/
    depends_on:
      - backend
  
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /redis/data:/root/redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16